<?php
/* File auto-generated by sh_imagesBuilder */
$mask = array (
  'x' => 
  array (
    0 => 0,
    1 => 3,
    2 => 74,
    3 => 269,
  ),
  'y' => 
  array (
    0 => 0,
    1 => 16,
    2 => 17,
    3 => 19,
    4 => 20,
    5 => 34,
  ),
);