<?php
/* File auto-generated by sh_imagesBuilder */
$mask = array (
  'x' => 
  array (
    0 => 0,
    1 => 3,
    2 => 87,
    3 => 90,
  ),
  'y' => 
  array (
    0 => 0,
    1 => 8,
    2 => 16,
    3 => 19,
    4 => 27,
    5 => 34,
  ),
);